"""Simple TF-IDF based recommender.

Load CSV (generated by `generate_dataset.py`) and build a text index over role+skills+summary.
Given a role query string, return top matching candidates and summary of sources.
"""
from typing import List, Dict, Any
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel


class Recommender:
    def __init__(self, dataset_csv: str):
        self.df = pd.read_csv(dataset_csv)
        # build a text field for matching
        self.df["search_text"] = (self.df["role"].fillna("") + " " +
                                   self.df["skills"].fillna("") + " " +
                                   self.df["summary"].fillna(""))
        self.vectorizer = TfidfVectorizer(max_features=20000, stop_words="english")
        self.tfidf_matrix = self.vectorizer.fit_transform(self.df["search_text"].astype(str))

    def recommend(self, role_query: str, top_n: int = 10) -> List[Dict[str, Any]]:
        """Return top_n candidate rows as dicts ordered by similarity."""
        query_vec = self.vectorizer.transform([role_query])
        cosine_similarities = linear_kernel(query_vec, self.tfidf_matrix).flatten()
        top_idx = cosine_similarities.argsort()[::-1][:top_n]
        results = []
        for idx in top_idx:
            row = self.df.iloc[idx].to_dict()
            row["score"] = float(cosine_similarities[idx])
            results.append(row)
        return results

    def recommend_sources(self, role_query: str, top_n_candidates: int = 200, top_k_sources: int = 5):
        """Return a summary of best sources to find prospects for the query.

        Approach:
        - find top_n_candidates by similarity
        - group them by `source`
        - rank sources by (count * avg_score) to prefer sources with both volume and relevance
        - return top_k_sources with a few sample profiles each
        """
        query_vec = self.vectorizer.transform([role_query])
        cosine_similarities = linear_kernel(query_vec, self.tfidf_matrix).flatten()
        top_idx = cosine_similarities.argsort()[::-1][:top_n_candidates]
        subset = self.df.iloc[top_idx].copy()
        subset["score"] = cosine_similarities[top_idx]
        group = subset.groupby("source").agg(count=("id", "count"), avg_score=("score", "mean"))
        group["rank_metric"] = group["count"] * group["avg_score"]
        group = group.sort_values("rank_metric", ascending=False)
        result = []
        for source, row in group.head(top_k_sources).iterrows():
            # provide sample ids and profile urls (no personal names)
            rows = subset[subset["source"] == source].sort_values("score", ascending=False).head(5)
            samples = rows[["id", "role", "skills", "experience_years", "location", "profile_url", "score"]].to_dict(orient="records")
            result.append({
                "source": source,
                "count": int(row["count"]),
                "avg_score": float(row["avg_score"]),
                "samples": samples,
            })
        return result

    def recommend_sources_only(self, role_query: str, top_n_candidates: int = 500, top_k_sources: int = 5, combine_with_data: bool = True):
        """Return only a ranked list of sources for the given role query.

        This method uses a small rule-based prior that maps role keywords to likely sources
        (for example: developer roles -> github, stackoverflow; sales roles -> apollo, linkedin).
        If `combine_with_data` is True and a dataset was provided, it will combine the prior
        with evidence from the dataset (how many top-matching candidates come from each source
        and their average relevance score).

        Returns a list of dicts: {source, score, prior, evidence_score, count}
        """
        # Known sources (a conservative default set). If dataset exists, include its sources.
        if hasattr(self, "df") and "source" in self.df.columns:
            known_sources = list(self.df["source"].dropna().unique())
        else:
            known_sources = ["linkedin", "github", "apollo", "angellist", "stackoverflow", "twitter"]

        # Lowercase role query for keyword matching
        q = role_query.lower()

        # Basic priors based on role keywords. Keys are keywords to search for in the role string.
        priors_map = {
            "engineer": {"github": 2.0, "stackoverflow": 1.5, "linkedin": 1.2},
            "developer": {"github": 2.2, "stackoverflow": 1.6, "linkedin": 1.1},
            "backend": {"github": 2.0, "stackoverflow": 1.4, "linkedin": 1.1},
            "frontend": {"github": 1.8, "stackoverflow": 1.6, "linkedin": 1.1},
            "data": {"github": 1.7, "linkedin": 1.6, "apollo": 1.1, "stackoverflow": 1.2},
            "machine learning": {"github": 1.8, "linkedin": 1.6, "apollo": 1.1},
            "ml": {"github": 1.8, "linkedin": 1.6},
            "sales": {"apollo": 2.2, "linkedin": 1.8, "twitter": 1.0},
            "account": {"apollo": 2.0, "linkedin": 1.7},
            "marketing": {"linkedin": 1.8, "twitter": 1.5, "angellist": 1.0},
            "product": {"linkedin": 1.9, "angellist": 1.0},
            "ux": {"linkedin": 1.6, "twitter": 1.3, "angellist": 1.2},
            "designer": {"linkedin": 1.6, "twitter": 1.3, "angellist": 1.2},
            "qa": {"linkedin": 1.3, "github": 1.2},
            "security": {"linkedin": 1.7, "github": 1.4},
        }

        # Start with neutral prior = 1.0 for each known source
        priors = {s: 1.0 for s in known_sources}

        # Apply priors based on keyword matches
        for kw, mapping in priors_map.items():
            if kw in q:
                for s, w in mapping.items():
                    if s in priors:
                        priors[s] *= w

        # Normalize priors to [0,1]
        max_prior = max(priors.values()) if priors else 1.0
        priors_norm = {s: (priors[s] / max_prior) for s in priors}

        # Evidence from dataset (optional)
        evidence = {s: 0.0 for s in known_sources}
        counts = {s: 0 for s in known_sources}
        if combine_with_data and hasattr(self, "tfidf_matrix"):
            # compute similarity and gather top candidates
            qvec = self.vectorizer.transform([role_query])
            from sklearn.metrics.pairwise import linear_kernel

            cosine_similarities = linear_kernel(qvec, self.tfidf_matrix).flatten()
            top_idx = cosine_similarities.argsort()[::-1][:top_n_candidates]
            subset = self.df.iloc[top_idx].copy()
            subset["score"] = cosine_similarities[top_idx]
            grp = subset.groupby("source").agg(count=("id", "count"), avg_score=("score", "mean"))
            if not grp.empty:
                # compute a normalized evidence score per source
                max_metric = (grp["count"] * grp["avg_score"]).max()
                for s in known_sources:
                    if s in grp.index:
                        metric = float((grp.loc[s, "count"] * grp.loc[s, "avg_score"]))
                        evidence[s] = metric / max_metric if max_metric > 0 else 0.0
                        counts[s] = int(grp.loc[s, "count"])

        # Combine prior and evidence: final_score = prior_norm * (0.4 + 0.6 * evidence)
        # This biases results toward priors when evidence is weak, but favors evidence when available.
        results = []
        for s in known_sources:
            ev = evidence.get(s, 0.0)
            pr = priors_norm.get(s, 0.0)
            if combine_with_data:
                final = pr * (0.4 + 0.6 * ev)
            else:
                final = pr
            results.append({
                "source": s,
                "score": float(final),
                "prior": float(pr),
                "evidence_score": float(ev),
                "count": int(counts.get(s, 0)),
            })

        results = sorted(results, key=lambda x: x["score"], reverse=True)
        return results[:top_k_sources]
